# Generated by Django 3.0.4 on 2020-03-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hits',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='artists', to='radio.Artists'),
        ),
    ]
